spring:
  datasource:
    url: ${CAVERA_DB_URL}
    username: ${CAVERA_DB_USERNAME}
    password: ${CAVERA_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8068

api:
  prefix: /cavera-control/api
  security:
    token:
      secret: "a lamb is always a lamb"

logging:
  level:
    org.springframework.security: DEBUG